FROM rust:1.62@sha256:5777f201f507075309c4d2d1c1e8d8219e654ae1de154c844341050016a64a0c as aptos-node

RUN apt-get update && apt-get -y install libclang-dev jq cmake curl npm --no-install-recommends

WORKDIR /tmp

RUN cargo install --git https://github.com/aptos-labs/aptos-core.git aptos --branch alin/move-keccak

RUN npm install -g n typescript ts-node
RUN n stable

COPY clients/js  /tmp/js
COPY aptos  /tmp/aptos

WORKDIR /tmp/js

RUN make install
