//@ts-nocheck
// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";

import { Channel as typeChannel} from "./types"
import { IdentifiedChannel as typeIdentifiedChannel} from "./types"
import { Counterparty as typeCounterparty} from "./types"
import { Packet as typePacket} from "./types"
import { PacketState as typePacketState} from "./types"
import { PacketId as typePacketId} from "./types"
import { Acknowledgement as typeAcknowledgement} from "./types"
import { PacketSequence as typePacketSequence} from "./types"

export {  };



export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Channel: getStructure(typeChannel.fromPartial({})),
						IdentifiedChannel: getStructure(typeIdentifiedChannel.fromPartial({})),
						Counterparty: getStructure(typeCounterparty.fromPartial({})),
						Packet: getStructure(typePacket.fromPartial({})),
						PacketState: getStructure(typePacketState.fromPartial({})),
						PacketId: getStructure(typePacketId.fromPartial({})),
						Acknowledgement: getStructure(typeAcknowledgement.fromPartial({})),
						PacketSequence: getStructure(typePacketSequence.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			IbcCoreChannelV1: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;