package common

import "github.com/certusone/wormhole/node/pkg/readiness"

const (
	ReadinessEthSyncing       readiness.Component = "ethSyncing"
	ReadinessSolanaSyncing    readiness.Component = "solanaSyncing"
	ReadinessTerraSyncing     readiness.Component = "terraSyncing"
	ReadinessAlgorandSyncing  readiness.Component = "algorandSyncing"
	ReadinessNearSyncing      readiness.Component = "nearSyncing"
	ReadinessAptosSyncing     readiness.Component = "aptosSyncing"
	ReadinessBSCSyncing       readiness.Component = "bscSyncing"
	ReadinessPolygonSyncing   readiness.Component = "polygonSyncing"
	ReadinessAvalancheSyncing readiness.Component = "avalancheSyncing"
	ReadinessOasisSyncing     readiness.Component = "oasisSyncing"
	ReadinessAuroraSyncing    readiness.Component = "auroraSyncing"
	ReadinessFantomSyncing    readiness.Component = "fantomSyncing"
	ReadinessKaruraSyncing    readiness.Component = "karuraSyncing"
	ReadinessAcalaSyncing     readiness.Component = "acalaSyncing"
	ReadinessKlaytnSyncing    readiness.Component = "klaytnSyncing"
	ReadinessCeloSyncing      readiness.Component = "celoSyncing"
	ReadinessMoonbeamSyncing  readiness.Component = "moonbeamSyncing"
	ReadinessNeonSyncing      readiness.Component = "neonSyncing"
	ReadinessTerra2Syncing    readiness.Component = "terra2Syncing"
	ReadinessInjectiveSyncing readiness.Component = "injectiveSyncing"
	ReadinessXplaSyncing      readiness.Component = "xplaSyncing"
	ReadinessPythNetSyncing   readiness.Component = "pythnetSyncing"
	ReadinessArbitrumSyncing  readiness.Component = "arbitrumSyncing"
	ReadinessOptimismSyncing  readiness.Component = "optimismSyncing"
	ReadinessWormchainSyncing readiness.Component = "wormchainSyncing"
)
