version: "2"
linters:
  default: none
  enable:
    - errcheck
    - forcetypeassert
    - gosec
    - govet
    - ineffassign
    - noctx
    - prealloc
    - staticcheck
    - unparam
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unused
        path: pkg/supervisor/supervisor_testhelpers.go
        text: ^func.*supervisor.*(waitSettle|waitSettleError).*$
      - path: pkg/txverifier/sui_test.go
        text: 'G101: Potential hardcoded credentials'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
