# syntax=docker.io/docker/dockerfile:1.3@sha256:42399d4635eddd7a9b8a24be879d2f9a930d0ed040a61324cfdf59ef1357b3b2
FROM docker.io/golang:1.23.3-bullseye@sha256:9e53abacfc22cd3df3e4ebcc04ac64951b71d2a38c52b690f3807af6a2000ed2 AS go-tools

RUN mkdir /app

COPY tools/build.sh /app/tools/
COPY tools/go.* /app/tools/

RUN --mount=type=cache,target=/root/.cache --mount=type=cache,target=/go \
	cd /app/tools && CGO_ENABLED=0 ./build.sh

# syntax=docker.io/docker/dockerfile:1.3@sha256:42399d4635eddd7a9b8a24be879d2f9a930d0ed040a61324cfdf59ef1357b3b2
FROM docker.io/golang:1.23.3-bullseye@sha256:9e53abacfc22cd3df3e4ebcc04ac64951b71d2a38c52b690f3807af6a2000ed2 AS go-build

COPY --from=go-tools /app /app

COPY buf.* /app
COPY proto /app/proto

RUN --mount=type=cache,target=/root/.cache \
	cd /app && \
	tools/bin/buf lint && \
	tools/bin/buf generate

FROM node:16-alpine@sha256:a1f9d027912b58a7c75be7716c97cfbc6d3099f3a97ed84aa490be9dee20e787 AS node-build

COPY --from=go-tools /app /app

COPY buf.* /app
COPY proto /app/proto

COPY tools/package.json /app/tools/
COPY tools/package-lock.json /app/tools/

RUN --mount=type=cache,target=/root/.cache --mount=type=cache,target=/root/.npm \
 	cd /app/tools && npm ci

RUN --mount=type=cache,target=/root/.cache \
	cd /app && \
	tools/bin/buf generate --template buf.gen.web.yaml

FROM scratch AS go-export
COPY --from=go-build /app/node/pkg/proto pkg/proto

FROM scratch AS node-export
COPY --from=node-build /app/sdk/js-proto-web/src sdk/js-proto-web/src
COPY --from=node-build /app/sdk/js-proto-node/src sdk/js-proto-node/src
