/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWormholeReceiver,
  IWormholeReceiverInterface,
} from "../IWormholeReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "signedVaas",
        type: "bytes[]",
      },
      {
        internalType: "bytes[]",
        name: "additionalData",
        type: "bytes[]",
      },
    ],
    name: "receiveWormholeMessages",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IWormholeReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IWormholeReceiverInterface {
    return new utils.Interface(_abi) as IWormholeReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWormholeReceiver {
    return new Contract(address, _abi, signerOrProvider) as IWormholeReceiver;
  }
}
