FROM node:iron-slim@sha256:cffed8cd39d6a380434e6d08116d188c53e70611175cd5ec7700f93f32a935a6

RUN mkdir -p /home/node/app/ethereum

WORKDIR /home/node/app/ethereum
RUN apt-get update && apt-get -y install \
  git make curl

COPY --from=ghcr.io/foundry-rs/foundry:nightly-d9e51e4807b62f101221a2fd36076c502399dbf9@sha256:f3237e283abbacec56edf54c2e422c5fe4d3b444eb10203e1e6d7ee089b11c4d \
  /usr/local/bin/forge \
  /usr/local/bin/cast \
  /usr/local/bin/anvil \
  /usr/local/bin/chisel \
  /bin/

COPY . .
ENV ENV=mainnet
ENV DEV=False
RUN make build

RUN npm run build:typescript

CMD ["node", "build-ts/ts-scripts/relayer/wormholeRelayer/verifyWormholeRelayerDeployedByteCode.js"]
