FROM node:iron-slim@sha256:cffed8cd39d6a380434e6d08116d188c53e70611175cd5ec7700f93f32a935a6

RUN mkdir -p /home/node/app/ethereum

WORKDIR /home/node/app/ethereum
RUN apt-get update && apt-get -y install \
  git make curl

COPY --from=ghcr.io/foundry-rs/foundry:nightly-7469d79cca59e0bb5f23563ac5a6bd5f2ec8c5e4@sha256:f84eabbe85ec74dd59464816bf65b8d1ec707c8fa78003aca66c13dad3a6fa42 \
  /usr/local/bin/forge \
  /usr/local/bin/cast \
  /usr/local/bin/anvil \
  /usr/local/bin/chisel \
  /bin/

COPY . .
ENV ENV=mainnet
ENV DEV=False
RUN make build

RUN npm run build:typescript

CMD ["node", "build-ts/ts-scripts/relayer/wormholeRelayer/verifyWormholeRelayerDeployedByteCode.js"]
