#!/usr/bin/env bash

# This script is a wrapper around the foundry Docker image.
# In an ideal world, we could just use anvil (and forge) directly, but there are regular
# upstream breaking changes in the nightly builds, and binaries of older
# versions are deleted frequently from their GitHub. The Docker releases are
# available for longer, so we just use those here.
#
# the DOCKER_ARGS environment variable can be used to pass additional args to docker.

set -eo pipefail

# This is a known-to-be-working build.
DOCKER_IMAGE="ghcr.io/foundry-rs/foundry:v1.0.0@sha256:d12a373ec950de170d5461014ef9320ba0fb6e0db6f87835999d0fcf3820370e"

args=$(printf '"%s" ' "$@")

docker run --rm -i $DOCKER_ARGS $DOCKER_IMAGE  "$args"
