FROM rust:1.90@sha256:64232e656c058f4468e8d024e990acff04f0fd5a5c0a88a574dc37773d7325c9 AS sui-build

# https://github.com/MystenLabs/sui/blob/0def7a08f11a2ec992e11123c5f5ac5e0279e0a0/docs/content/guides/developer/getting-started/sui-install.mdx#all-linux-prerequisites
RUN apt-get update && apt-get install -y curl git-all cmake gcc libssl-dev pkg-config libclang-dev libpq-dev build-essential

# https://github.com/MystenLabs/sui/releases/tag/testnet-v1.63.2
RUN cargo install --locked --git https://github.com/MystenLabs/sui.git --rev 0def7a08f11a2ec992e11123c5f5ac5e0279e0a0 sui

FROM rust:1.90@sha256:64232e656c058f4468e8d024e990acff04f0fd5a5c0a88a574dc37773d7325c9 AS sui-node

WORKDIR /tmp

COPY --from=sui-build /usr/local/cargo/bin/sui /bin/sui

RUN apt-get update && apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

ARG NODE_MAJOR=18
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

RUN apt-get update
RUN apt-get install nodejs -y
