FROM rust:1.62@sha256:5777f201f507075309c4d2d1c1e8d8219e654ae1de154c844341050016a64a0c as sui-node

RUN apt-get update && apt-get -y install libclang-dev jq cmake curl npm gcc g++ make lld

WORKDIR /tmp

COPY sui/scripts/node_builder.sh  /tmp
RUN /tmp/node_builder.sh

FROM rust:1.62@sha256:5777f201f507075309c4d2d1c1e8d8219e654ae1de154c844341050016a64a0c as export-stage

RUN apt-get update
RUN apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

ARG NODE_MAJOR=18
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

RUN apt-get update
RUN apt-get install nodejs -y

COPY --from=sui-node /usr/local/cargo/bin/sui /bin/sui
COPY --from=sui-node /usr/local/cargo/bin/sui-faucet /bin/sui-faucet
COPY --from=sui-node /usr/local/cargo/bin/sui-node /bin/sui-node
