FROM ghcr.io/wormhole-foundation/sui:0.11.0-rh@sha256:0eb82ae5c7a3233eeae263f06d52fbe13304d89492eba28544b533553082fd99 as sui-node
FROM scratch
COPY --from=sui-node /root/.cargo/bin/sui .
COPY --from=sui-node /root/.cargo/bin/sui-faucet .
COPY --from=sui-node /root/.cargo/bin/rpc-server .
