FROM ghcr.io/wormhole-foundation/sui:0.11.0@sha256:b6a0149349a8be346bea6d71090d50571ffac32c956fb7a5fb2e1e959780c837 as sui-node
FROM scratch
COPY --from=sui-node /usr/local/cargo/bin/sui .
COPY --from=sui-node /usr/local/cargo/bin/sui-faucet .
COPY --from=sui-node /usr/local/cargo/bin/rpc-server .
