src/
data/
.vscode/
.vim/
.github/
cache/
lib/
out/
tmp/
verifiable-evm-build/

.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions

ts-pkgs/deploy
ts-pkgs/peer-e2e
ts-pkgs/tss-definitions
ts-pkgs/peer-client

**/ts-build

.gitignore
.gitmodules
*.sublime-*
*.awk
foundry.toml
guardian_key.txt
Makefile
README.md
eslint.config.mjs

*Dockerfile
*dockerignore