FROM node:22.16-bullseye-slim@sha256:550b434f7edc3a1875860657a3e306752358029c957280809ae6395ab296faeb

RUN apt-get update && apt-get -y install \
  git python3 make curl netcat

RUN mkdir -p /app
WORKDIR /app

COPY sdk/js-query/package.json sdk/js-query/package-lock.json ./sdk/js-query/
RUN --mount=type=cache,uid=1000,gid=1000,target=/home/node/.npm \
    npm ci --prefix sdk/js-query
COPY sdk/js-query ./sdk/js-query
RUN npm run build --prefix sdk/js-query

COPY testing ./testing

WORKDIR /app/testing
