FROM node:22.16-bullseye-slim@sha256:550b434f7edc3a1875860657a3e306752358029c957280809ae6395ab296faeb

RUN apt-get update && apt-get -y install \
  git python3 make curl netcat

RUN mkdir -p /app
WORKDIR /app

COPY spydk/js/package.json spydk/js/package-lock.json ./spydk/js/
RUN --mount=type=cache,uid=1000,gid=1000,target=/home/node/.npm \
    npm ci --prefix spydk/js
COPY spydk/js ./spydk/js
RUN npm run build --prefix spydk/js

COPY testing ./testing

WORKDIR /app/testing
