FROM node:19.6.1-slim@sha256:e684615bdfb71cb676b3d0dfcc538c416f7254697d8f9639bd87255062fd1681

RUN apt-get update && apt-get -y install \
  git python3 make curl netcat g++

RUN mkdir -p /app
WORKDIR /app

COPY spydk/js/package.json spydk/js/package-lock.json ./spydk/js/
RUN --mount=type=cache,uid=1000,gid=1000,target=/home/node/.npm \
    npm ci --prefix spydk/js
COPY spydk/js ./spydk/js
RUN npm run build --prefix spydk/js

COPY testing ./testing

WORKDIR /app/testing
