FROM node:18-alpine@sha256:44aaf1ccc80eaed6572a0f2ef7d6b5a2982d54481e4255480041ac92221e2f11

RUN apk update && apk add g++ make python3 curl netcat git 

RUN npm i typescript -g
RUN curl -L https://foundry.paradigm.xyz | bash 
RUN $HOME/.foundry/bin/foundryup
RUN ls $HOME/.foundry/bin
RUN mv /root/.foundry/bin/forge /bin/forge

RUN mkdir -p /app
WORKDIR /app

COPY ethereum/package.json ethereum/package-lock.json ./ethereum/
RUN --mount=type=cache,uid=1000,gid=1000,target=/home/node/.npm \
  npm ci --prefix ethereum
COPY ethereum ./ethereum

WORKDIR /app/ethereum
RUN make forge_dependencies
WORKDIR /app

COPY solana/idl ./solana/idl/

COPY sdk/js/package.json sdk/js/package-lock.json  ./sdk/js/
RUN --mount=type=cache,uid=1000,gid=1000,target=/home/node/.npm \
  npm ci --prefix sdk/js
COPY sdk/js ./sdk/js
RUN npm run build --prefix sdk/js

COPY testing ./testing

WORKDIR /app/testing
