FROM --platform=linux/amd64 ghcr.io/foundry-rs/foundry:v1.0.0@sha256:d12a373ec950de170d5461014ef9320ba0fb6e0db6f87835999d0fcf3820370e as foundry
FROM node:22.17-bullseye-slim@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb

RUN apt-get update && apt-get -y install \
  git python3 make curl netcat vim

RUN npm i typescript -g
COPY --from=foundry /usr/local/bin/forge /bin/forge

RUN mkdir -p /app
WORKDIR /app

COPY ethereum/package.json ethereum/package-lock.json ./ethereum/
RUN --mount=type=cache,uid=1000,gid=1000,target=/home/node/.npm \
  npm ci --prefix ethereum
COPY ethereum ./ethereum

COPY relayer/ethereum/package.json relayer/ethereum/package-lock.json ./relayer/ethereum/
RUN --mount=type=cache,uid=1000,gid=1000,target=/home/node/.npm \
  npm ci --prefix relayer/ethereum
COPY relayer/ethereum ./relayer/ethereum

COPY solana/idl ./solana/idl/

COPY sdk/js/package.json sdk/js/package-lock.json  ./sdk/js/
RUN --mount=type=cache,uid=1000,gid=1000,target=/home/node/.npm \
  npm ci --prefix sdk/js
COPY sdk/js ./sdk/js
RUN npm run build --prefix sdk/js

COPY testing ./testing

WORKDIR /app/testing
