FROM node:19.6.1-slim@sha256:a1ba21bf0c92931d02a8416f0a54daad66cb36a85d2b73af9d73b044f5f57cfc

RUN apt-get update && apt-get -y install \
  git python3 make curl netcat

RUN mkdir -p /app
WORKDIR /app

COPY sdk/js-connect/package.json sdk/js-connect/ci-config.js sdk/js-connect/jest.config.ts sdk/js-connect/package-lock.json sdk/js-connect/buffer-layout.d.ts ./sdk/js-connect/

COPY sdk/js-connect/core ./sdk/js-connect/core
COPY sdk/js-connect/token_bridge ./sdk/js-connect/token_bridge

RUN --mount=type=cache,uid=1000,gid=1000,target=/home/node/.npm \
    npm ci --workspaces --prefix sdk/js-connect

RUN npm run build --prefix sdk/js-connect

COPY testing ./testing

WORKDIR /app/testing
