/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type WormholeQuery = {
  verify_quorum: {
    data: Binary;
    guardian_set_index: number;
    signatures: Signature[];
  };
} | {
  verify_signature: {
    data: Binary;
    guardian_set_index: number;
    signature: Signature;
  };
} | {
  calculate_quorum: {
    guardian_set_index: number;
  };
};
export type Binary = string;
export interface Signature {
  index: number;
  signature: Binary;
}