FROM debian@sha256:2ce44bbc00a79113c296d9d25524e15d423b23303fdbbe20190d2f96e0aeb251 as build

RUN apt-get update && apt-get install -y curl \
    make \
    build-essential

WORKDIR /app
COPY ./setup-rust.sh .
RUN ./setup-rust.sh

COPY . .

RUN ./build-contracts.sh

FROM node:16-alpine@sha256:004dbac84fed48e20f9888a23e32fa7cf83c2995e174a78d41d9a9dd1e051a20 AS deploy

WORKDIR /app
COPY package.json .
COPY package-lock.json .
COPY .env .
COPY devnet_deploy.sh .
COPY devnet_deploy.ts .
COPY --from=build /app/contracts/*/target/wasm32-unknown-unknown/release/*.wasm .

# mount the buildkit cache on npm's cache dir, install dependencies
RUN --mount=type=cache,target=/root/.npm npm ci --production


