FROM rust:1.60@sha256:48d3b5baf199dc7c378e775c47b0c40aaf7d8b23eaf67e15b095bbdaaecd1f10 AS near-contracts-build

ADD . .
RUN make clean
RUN ./build-contracts.sh

FROM scratch AS near-contracts-export

COPY --from=near-contracts-build /tmp/contracts/token-bridge/target/wasm32-unknown-unknown/release/near_token_bridge.wasm near_token_bridge.wasm
COPY --from=near-contracts-build /tmp/contracts/wormhole/target/wasm32-unknown-unknown/release/near_wormhole.wasm near_wormhole.wasm
COPY --from=near-contracts-build /tmp/contracts/ft/target/wasm32-unknown-unknown/release/near_ft.wasm near_ft.wasm

