data/
.vscode/
.vim/
.github/
cache/
lib/
out/
tmp/
verifiable-evm-build/

ts-pkgs/
!ts-pkgs/peer-e2e

src/solana

**/ts-build

.gitignore
.gitmodules
*.sublime-*
*.awk
guardian_key.txt
README.md
eslint.config.mjs

.yarn/
package.json
tsconfig.json
yarn.lock
.pnp.*

*Dockerfile
*dockerignore