FROM golang:1.22.5@sha256:86a3c48a61915a8c62c0e1d7594730399caa3feb73655dfe96c7bc17710e96cf AS base

WORKDIR /home

# Install dependencies
RUN apt update && \
    apt-get install -y \
        build-essential \
        ca-certificates \
        curl

# Enable faster module downloading.
ENV GOPROXY https://proxy.golang.org



## CLI BUILDER STAGE
FROM base AS cli-builder

WORKDIR /ignite

# Git clone https://github.com/ignite/cli version v0.27.2
RUN git clone --branch release/v0.27.2 https://github.com/ignite/cli.git

WORKDIR /ignite/cli

RUN sed -i 's/go 1.19/go 1.22.5/g' go.mod
RUN go mod tidy

# Install ignite binary & verify installation
RUN --mount=type=cache,target=/root/.cache/go-build go install -v ./...
RUN ignite version



## WORMCHAIN BUILDER STAGE
FROM base AS wormchain-builder

# Define 'tendermint' user (same as in the official ignite image)
RUN useradd -ms /bin/bash tendermint
USER tendermint

# Copy wormchain into container
COPY --chown=tendermint:tendermint wormchain /wh/apps/wormchain
COPY --chown=tendermint:tendermint sdk /wh/apps/sdk

# Set working directory
WORKDIR /wh/apps/wormchain

# Copy ignite cli binary
COPY --from=cli-builder /go/bin/ignite /usr/bin 

# Verify ignite setup
RUN ignite doctor



## GO PROTO BUILDER STAGE
FROM wormchain-builder AS ignite-go-build
# Ignite only likes minor versions in go.mod
RUN sed -i 's/go 1.22.5/go 1.22/g' go.mod
RUN ignite generate proto-go



## GO EXPORT STAGE
FROM scratch AS go-export
COPY --from=ignite-go-build /wh/apps/wormchain/x/wormhole/types /x/wormhole/types
COPY --from=ignite-go-build /wh/apps/wormchain/x/tokenfactory/types /x/tokenfactory/types
COPY --from=ignite-go-build /wh/apps/wormchain/x/ibc-composability-mw/types /x/ibc-composability-mw/types



## VUE BUILDER STAGE
FROM wormchain-builder AS ignite-vue-build
# Ignite only likes minor versions in go.mod
RUN sed -i 's/go 1.22.5/go 1.22/g' go.mod
RUN NODE_OPTIONS="" ignite generate vuex



## VUE EXPORT STAGE
FROM scratch AS vue-export
COPY --from=ignite-vue-build /wh/apps/wormchain/vue /vue