#!/bin/bash

GUARDIAN_ADDR=0xbeFA429d57cD18b7F8A4d91A2da9AB4AF05d0FBe
WORMHOLE_ADDR=0x251011524cd0f76881f16e7c2d822f0c1c9510bfd2430ba24e1b3d52796df204
TOKEN_BRIDGE_ADDR=0x4450040bc7ea55def9182559ceffc0652d88541538b30a43477364f475f4a4ed

# we already funded some accounts manually using:
# aptos account --fund-with-faucet --account ...
# worm aptos faucet

# Deploy deployer contract for creating resource accounts
worm aptos deploy --network testnet ../deployer

# Deploy wormhole
worm aptos deploy-resource wormhole --network testnet ../wormhole
# Initialise wormhole
worm aptos init-wormhole --network testnet -g $GUARDIAN_ADDR --contract-address $WORMHOLE_ADDR

# Deploy & initialise (with `init_module`) token_bridge
worm aptos deploy-resource token_bridge --network testnet ../token_bridge
# Initialise token-bridge
worm aptos init-token-bridge --network testnet --contract-address $TOKEN_BRIDGE_ADDR

# Deploy example program for sending messages
worm aptos deploy --network testnet ../examples/core_messages

