#!/bin/bash

# This script upgrades the token bridge in local devnet by generating a
# governance VAA and submitting it

HASH=$(worm aptos hash-contracts ../token_bridge/)
# devnet guardian secret..
GUARDIAN_SECRET=cfb12303a19cde580bb4dd771639b0d26bc68353645571a8cff516ab2ee113a0
CONTRACT_ADDR=0x4450040bc7ea55def9182559ceffc0652d88541538b30a43477364f475f4a4ed
VAA=$(worm generate upgrade -c aptos -a $HASH -m TokenBridge -g $GUARDIAN_SECRET)

echo "Submitting VAA: $VAA"

worm submit --network devnet "$VAA" --contract-address $CONTRACT_ADDR
worm aptos upgrade ../token_bridge --network devnet --contract-address 0x4450040bc7ea55def9182559ceffc0652d88541538b30a43477364f475f4a4ed
