#!/bin/bash

set -euo pipefail

# Get the directory where this script lives
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RPC_URL="http://127.0.0.1:8545"
VERIFIER_ADDRESS="0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
SMALL_SCHNORR_VAA="AgAAAABBz40w68yAC2VerRXMlgFNNsQka/tfpkiHxKBYGLAq+nSD5RFfGak3OcS5zk6SuuGRou9LAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
SMALL_MULTISIG_VAA="AQAAAAABAH1hXF/HkA1FhOJTsy3ItWDUGPXUgFpw520Q4T5NgwfNWxKv1xi+WcRQ0MrybHukXIlZ35vscKjl5uncc8yh8u8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="

yarn tsx "$SCRIPT_DIR/../verifyVaa.ts" --rpc $RPC_URL --verifier $VERIFIER_ADDRESS --vaa $SMALL_SCHNORR_VAA
yarn tsx "$SCRIPT_DIR/../verifyVaa.ts" --rpc $RPC_URL --verifier $VERIFIER_ADDRESS --vaa $SMALL_MULTISIG_VAA
