{
 "title": "Wormhole v2",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(wormhole_eth_current_height, instance)"
    }
   },
   {
    "name": "node_name",
    "label": "node_name",
    "query": {
     "query": "label_values(wormhole_network_node_height, node_name)"
    }
   },
   {
    "name": "addr",
    "label": "addr",
    "query": {
     "query": "label_values(wormhole_observations_signed_by_guardian_total, addr)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Height info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ETH Blocks/s",
   "type": "timeseries",
   "description": "Current Ethereum block height",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(wormhole_eth_current_height{instance=~\"$instance\", eth_network=\"eth\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Solana Slots/s",
   "type": "timeseries",
   "description": "Current Solana slot height",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(wormhole_solana_current_height{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{commitment}}"
    }
   ]
  },
  {
   "title": "Terra Slots/s",
   "type": "timeseries",
   "description": "Current Terra slot height (at default commitment level, not the level used for observations)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(wormhole_terra_current_height{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "BSC Blocks/s",
   "type": "timeseries",
   "description": "Current Ethereum block height",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(wormhole_eth_current_height{instance=~\"$instance\", eth_network=\"bsc\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{eth_network}}"
    }
   ]
  },
  {
   "title": "Network ETH Height",
   "type": "timeseries",
   "description": "Network height of the given guardian node per network(ethereum)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "wormhole_network_node_height{instance=~\"$instance\", network=\"ethereum\", node_name=~\"$node_name\"} > 0",
     "legendFormat": "{{ node_name }} - {{instance}}"
    }
   ]
  },
  {
   "title": "Network Solana Height",
   "type": "timeseries",
   "description": "Network height of the given guardian node per network(solana)",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "wormhole_network_node_height{instance=~\"$instance\", network=\"solana\", node_name=~\"$node_name\"} > 0",
     "legendFormat": "{{ node_name }} - {{instance}}"
    }
   ]
  },
  {
   "title": "Network Terra Height",
   "type": "timeseries",
   "description": "Network height of the given guardian node per network(terra)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "wormhole_network_node_height{instance=~\"$instance\", network=\"terra\", node_name=~\"$node_name\"} > 0",
     "legendFormat": "{{ node_name }} - {{instance}}"
    }
   ]
  },
  {
   "title": "Network BSC Height",
   "type": "timeseries",
   "description": "Network height of the given guardian node per network(bsc)",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "wormhole_network_node_height{instance=~\"$instance\", network=\"bsc\", node_name=~\"$node_name\"} > 0",
     "legendFormat": "{{ node_name }} - {{instance}}"
    }
   ]
  },
  {
   "title": "Aggregation info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of errors the given guardian node encountered per network",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(wormhole_network_node_errors_count{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "unobserved - {{instance}}"
      }
     ]
    },
    {
     "title": "Aggregation State Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "wormhole_aggregation_state_entries{instance=~\"$instance\"}",
       "legendFormat": "count - {{instance}}"
      }
     ]
    },
    {
     "title": "Message Observations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(wormhole_eth_messages_observed_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ethereum (found) - {{instance}}"
      },
      {
       "expr": "increase(wormhole_eth_messages_confirmed_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ethereum (confirmed) - {{instance}}"
      },
      {
       "expr": "increase(wormhole_solana_observations_confirmed_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "solana (confirmed) - {{instance}}"
      },
      {
       "expr": "increase(wormhole_terra_messages_confirmed_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "terra (confirmed) - {{instance}}"
      }
     ]
    },
    {
     "title": "Lockup Observations (increase)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(wormhole_eth_messages_observed_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ethereum (found) - {{instance}}"
      },
      {
       "expr": "increase(wormhole_eth_lockups_confirmed_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ethereum (confirmed) - {{instance}}"
      },
      {
       "expr": "increase(wormhole_solana_lockups_confirmed_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "solana (confirmed) - {{instance}}"
      },
      {
       "expr": "increase(wormhole_terra_lockups_confirmed_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "terra (confirmed)  - {{instance}}"
      }
     ]
    },
    {
     "title": "Lockup Observations ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "wormhole_eth_messages_observed_total{instance=~\"$instance\"}",
       "legendFormat": "ethereum (found) - {{instance}}"
      },
      {
       "expr": "wormhole_eth_lockups_confirmed_total{instance=~\"$instance\"}",
       "legendFormat": "ethereum (confirmed) - {{instance}}"
      },
      {
       "expr": "wormhole_solana_lockups_confirmed_total{instance=~\"$instance\"}",
       "legendFormat": "solana (confirmed) - {{instance}}"
      },
      {
       "expr": "wormhole_terra_lockups_confirmed_total{instance=~\"$instance\"}",
       "legendFormat": "terra (confirmed)  - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "P2P Messages Received/s",
     "type": "timeseries",
     "description": "Total number of p2p pubsub broadcast messages received",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(wormhole_p2p_broadcast_messages_received_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{ type }} - {{instance}}"
      }
     ]
    },
    {
     "title": "Watcher Error Count",
     "type": "timeseries",
     "description": "Total number connection errors",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(wormhole_eth_connection_errors_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{eth_network}} - {{ reason }} - {{instance}}"
      },
      {
       "expr": "increase(wormhole_solana_connection_errors_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Solana - {{ reason }} - {{instance}}"
      },
      {
       "expr": "rate(wormhole_terra_connection_errors_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Terra - {{ reason }} - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of errors the given guardian node encountered on Solana",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "wormhole_network_node_errors_count{instance=~\"$instance\", network=~\"solana\", node_name=~\"$node_name\"}",
       "legendFormat": "{{ node_name }}  - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of errors the given guardian node encountered on Ethereum",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "wormhole_network_node_errors_count{instance=~\"$instance\", network=~\"ethereum\", node_name=~\"$node_name\"}",
       "legendFormat": "{{ node_name }} - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of errors the given guardian node encountered on BSC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "wormhole_network_node_errors_count{instance=~\"$instance\", network=~\"bsc\", node_name=~\"$node_name\"}",
       "legendFormat": "{{ node_name }} - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of errors the given guardian node encountered on Terra",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "wormhole_network_node_errors_count{instance=~\"$instance\", network=~\"terra\", node_name=~\"$node_name\"}",
       "legendFormat": "{{ node_name }} - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Balance info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Solana Fee Payer Balance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "wormhole_solana_fee_account_balance_lamports{instance=~\"$instance\"}",
       "legendFormat": "lamport (1B = 1 SOL) - {{instance}}"
      }
     ]
    },
    {
     "title": "Terra Fee Payer Balance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "wormhole_terra_fee_account_balance_lamports{instance=~\"$instance\"}",
       "legendFormat": "token - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Signatures info (set instance filter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Observations by Guardian",
     "type": "timeseries",
     "description": "Total number of signed and verified VAA observations grouped by guardian address",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(wormhole_observations_signed_by_guardian_total{instance=~\"$instance\", addr=~\"$addr\"}[$__rate_interval])",
       "legendFormat": "{{ addr }}"
      }
     ]
    },
    {
     "title": "Missing Signatures",
     "type": "timeseries",
     "description": "Total number of signatures produced by a validator, counted after waiting a fixed amount of time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(wormhole_aggregation_state_settled_signatures_total{status!=\"present\", instance=~\"$instance\", addr=~\"$addr\"}[1h])",
       "legendFormat": "{{ addr }} - from {{ origin }}"
      }
     ]
    },
    {
     "title": "Missing Signatures (except unknown)",
     "type": "timeseries",
     "description": "Total number of signatures produced by a validator, counted after waiting a fixed amount of time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(wormhole_aggregation_state_settled_signatures_total{status!=\"present\", origin!=\"unknown\", instance=~\"$instance\", addr=~\"$addr\"}[1h])",
       "legendFormat": "{{ addr }} - from {{ origin }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Solana Query Latency",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "sum(increase(wormhole_solana_query_latency_bucket{instance=~\"$instance\"}[$__interval])) by (le)"
      }
     ]
    },
    {
     "title": "Ethereum Query Latency",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 77 },
     "targets": [
      {
       "expr": "sum(increase(wormhole_eth_query_latency_bucket{instance=~\"$instance\"}[$__interval])) by (le)"
      }
     ]
    },
    {
     "title": "Terra Query Latency",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 77 },
     "targets": [
      {
       "expr": "sum(increase(wormhole_terra_query_latency_bucket{instance=~\"$instance\"}[$__interval])) by (le)"
      }
     ]
    },
    {
     "title": "BSC Query Latency",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 77 },
     "targets": [
      {
       "expr": "sum(increase(wormhole_eth_query_latency_bucket{instance=~\"$instance\", eth_network=\"bsc\"}[$__interval])) by (le)"
      }
     ]
    }
   ]
  },
  {
   "title": "Debug",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus target status ",
     "type": "state-timeline",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "up{job=\"wormhole\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node uptime",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "days" } },
     "targets": [
      {
       "expr": "(time() - process_start_time_seconds{instance=~\"$instance\"}) /86400",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "QUIC connection errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "quic_connection_errors_total{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - {{error_code}} - {{side}}"
      }
     ]
    },
    {
     "title": "Resident memory size in bytes.",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}