#!/usr/bin/env bash
# List of env values consumed by Jest
# Here we can set what value these env variables should have while running jest testing environment
ETH_KEY=0xdaea9603039234fa8a0c63d60b8b2b6ac5cdcfa4a2707904a31f3e70f38e10e1
ETH_KEY_TESTNET=0xdaea9603039234fa8a0c63d60b8b2b6ac5cdcfa4a2707904a31f3e70f38e10e1
TERRA_MNEMONIC=squirrel future level fan world organ daring thing color orange sausage cross fault interest blast wink audit unfair satoshi solution track indoor sun edit
SOLANA_KEY=4MAxm1Mz438N1acLiSv3ndVmd1nxiY3nXWgAr7UzXoKdc3U9gi1tQukUwDf7e1fvAnuDNF97Z7e8ndM53xXbh6kf
SOLANA_KEY_TESTNET=4MAxm1Mz438N1acLiSv3ndVmd1nxiY3nXWgAr7UzXoKdc3U9gi1tQukUwDf7e1fvAnuDNF97Z7e8ndM53xXbh6kf
ALGORAND_KEY=year crumble opinion local grid injury rug happy away castle minimum bitter upon romance federal entire rookie net fabric soft comic trouble business above talent
NEAR_KEY=2aN52kFK84Uo5Z5A5RE1wc9gNyhUfMtAernzHSzjN5hotoYjZJVVbcXJRewuc6HbBv4ACaRVmhoCnSeksdJvr5jU
APTOS_KEY=bb14af025d226288a3488b4433cf5cb54d6a710365a2d95ac6ffbd9b9198a86a
SUI_KEY=ACb4xyRkR24eyPbko3m3B/3TiiTEsP6O+ReMbYDJB2s2
XPLA_KEY=squirrel future level fan world organ daring thing color orange sausage cross fault interest blast wink audit unfair satoshi solution track indoor sun edit
SEI_KEY_TESTNET=step item design blush napkin dog bid express horse abuse kiwi grow
INJECTIVE_KEY=squirrel future level fan world organ daring thing color orange sausage cross fault interest blast wink audit unfair satoshi solution track indoor sun edit