/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface NFTBridgeSetupInterface extends utils.Interface {
  functions: {
    "setup(address,uint16,address,uint16,bytes32,address,uint8,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "setup"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "setup",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "setup", data: BytesLike): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface NFTBridgeSetup extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NFTBridgeSetupInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    setup(
      implementation: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      wormhole: PromiseOrValue<string>,
      governanceChainId: PromiseOrValue<BigNumberish>,
      governanceContract: PromiseOrValue<BytesLike>,
      tokenImplementation: PromiseOrValue<string>,
      finality: PromiseOrValue<BigNumberish>,
      evmChainId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  setup(
    implementation: PromiseOrValue<string>,
    chainId: PromiseOrValue<BigNumberish>,
    wormhole: PromiseOrValue<string>,
    governanceChainId: PromiseOrValue<BigNumberish>,
    governanceContract: PromiseOrValue<BytesLike>,
    tokenImplementation: PromiseOrValue<string>,
    finality: PromiseOrValue<BigNumberish>,
    evmChainId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    setup(
      implementation: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      wormhole: PromiseOrValue<string>,
      governanceChainId: PromiseOrValue<BigNumberish>,
      governanceContract: PromiseOrValue<BytesLike>,
      tokenImplementation: PromiseOrValue<string>,
      finality: PromiseOrValue<BigNumberish>,
      evmChainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
  };

  estimateGas: {
    setup(
      implementation: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      wormhole: PromiseOrValue<string>,
      governanceChainId: PromiseOrValue<BigNumberish>,
      governanceContract: PromiseOrValue<BytesLike>,
      tokenImplementation: PromiseOrValue<string>,
      finality: PromiseOrValue<BigNumberish>,
      evmChainId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    setup(
      implementation: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      wormhole: PromiseOrValue<string>,
      governanceChainId: PromiseOrValue<BigNumberish>,
      governanceContract: PromiseOrValue<BytesLike>,
      tokenImplementation: PromiseOrValue<string>,
      finality: PromiseOrValue<BigNumberish>,
      evmChainId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
