name: Publish flattened EVM contracts as an artifact for verification purposes

on:
  # The action can be triggered manually or whenever a tag with the name 'evm-*'
  # is pushed
  workflow_dispatch:
  push:
    tags:
      - 'evm-*'

permissions:
  contents: read

jobs:
  publish-artifacts:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Flatten contracts
        run: cd ethereum && make flattened

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: flattened-contracts
          path: ethereum/flattened
