name: locked-in
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  locked-in:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: asymmetric-research/locked-in@0d496b06be33cd08fff568bd2e0d281caee2149a
        with:
          commit: 0d496b06be33cd08fff568bd2e0d281caee2149a
