---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ccq-rate-limits
data:
  ccq-rate-limits.json: |
    {
      "EVM": {
        "500": "1 QPS",
        "50": "1 QPM"
      },
      "Solana": {
        "1250": "1 QPS",
        "125": "1 QPM"
      }
    }
